name: Build AdGuard Filters
permissions:                # Job-level permissions configuration starts here
  contents: write           # 'write' access to repository contents
  pull-requests: write      # 'write' access to pull requests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */8 * * *"

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: Build AdGuard Filters
        run: |
          bash scripts/fetch-filters.sh
          bash scripts/build-filters.sh
          date +%s > timestamp
          git config user.name "${{ vars.GIT_USER }}"
          git config user.email "${{ vars.GIT_EMAIL }}"
          git commit -a -m "Update AdGuard filters $(date +'%Y-%m-%d %H:%M:%S') RPC"
      - name: Push Filters
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          branch: master