name: Build AdGuard Filters

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */8 * * *"

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build AdGuard Filters
        run: |
          date +%s > timestamp
          git config --global user.name "${{ env.GIT_USER }}"
          git config --global user.email "${{ env.GIT_EMAIL }}"
          git commit -m "Update AdGuard filters $(date +'%Y-%m-%d %H:%M:%S') RPC"
          git push