name: Build AdGuard Filters

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */8 * * *"

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build AdGuard Filters
        run: |
          bash scripts/fetch-filters.sh
          bash scripts/build-filters.sh
          git commit -m "Update AdGuard filters $(date +'%Y-%m-%d %H:%M:%S') RPC"
          git push